% analyze_SWR_homecage.m
% This script performs two independent analyses of SWR (sharp‑wave ripple)
% events detected from home‑cage recordings.
%   Part 1: Counts the number of SWRs per channel (averaged across channels)
%           for a given animal and day.
%   Part 2: Computes the average duration and peak power of SWRs for a
%           specific animal and channel.
%
% The script relies on pre‑computed SWR detection results stored in .mat
% files (generated by bz_FindRipples) under a structured folder hierarchy.

%% ===================== PART 1: SWR Counts ================================
% This section loads SWR data for channels 33‑64, sums the number of ripple
% events across all channels, and then divides by 32 to get the average
% count per channel for each day.

clear;
Almid = 20;              % Animal index (used to select from homecage.filename)
fq = 1000;               % Sampling frequency (not used directly, kept for reference)
% fnameplus = 5;         % (Commented out) Optional date offset

cd('Y:\数据备份\consolidation');
load('homecage.mat');    % Loads variable 'homecage' with filename lists and metadata
load('timestamp.mat');   % Loads general timestamp info (not used directly)

% Preallocate array to store average SWR count per day (10 days)
rrd = zeros(10, 1);

% Loop over days (assuming 10 days of recording)
for DayN = 1:10
    % Get the filename (without extension) for this animal and day
    filename = homecage.filename(Almid, 1).list{DayN};

    tic   % Start timer to measure processing time

    % Loop over channels 33 to 64 (32 channels total)
    for ii = 33:64
        % Build the path to the SWR .mat file for this channel and day
        % Note: 'day(DayN)' is assumed to return a string like 'day1', 'day2', etc.
        %       If undefined, this will cause an error – check your environment.
        load([cd, '\', filename(1:homecage.lengthTitlist(Almid)), '\SWR\', ...
             char(day(DayN)), '\', num2str(ii, '%02d'), 'SWR.mat']);

        % 'r' is the ripple structure loaded from the .mat file.
        % Accumulate the total number of detected ripples (r.peaks)
        rrd(DayN) = rrd(DayN) + length(r.peaks);
    end

    % Display the total count for this day (before averaging)
    rrd(DayN)
    toc   % Stop timer and display elapsed time
end

% Average the total count across the 32 channels to get per‑channel mean
rrd = rrd / 32;

% (This line is likely a debug call; it prints the length of the LFP used
%  for detection, but it may produce an error if 'r' is not defined.)
% length(r.detectorinfo.edtectionparms.lfp);

%% ===================== PART 2: SWR Duration and Power ====================
% This section loads SWR data for a single channel (37) of a different animal
% and computes the average duration (in ms) and average normalized peak power
% of all detected SWR events.

clear;   % Clear workspace to start fresh

Almid = 19;              % Different animal index
fq = 1000;               % Sampling frequency (kept for reference)
% fnameplus = 5;         % (Commented out)

cd('Y:\数据备份\consolidation');
load('homecage.mat');
load('timestamp.mat');

% Preallocate a 10x2 matrix: column 1 = mean duration (ms), column 2 = mean normalized power
rrd = zeros(10, 2);

% Loop over days
for DayN = 1:10
    filename = homecage.filename(Almid, 1).list{DayN};
    tic

    % Only process channel 37 (you can change this if needed)
    for ii = 37:37
        load([cd, '\', filename(1:homecage.lengthTitlist(Almid)), '\SWR\', ...
             char(day(DayN)), '\', num2str(ii, '%02d'), 'SWR.mat']);

        % Compute the mean duration of all ripples (timestamps(:,2) - timestamps(:,1))
        % Convert from seconds to milliseconds (×1000)
        tempp = mean(r.timestamps(:, 2) - r.timestamps(:, 1)) * 1000;
        rrd(DayN, 1) = tempp;

        % Store the mean normalized peak power (r.peakNormedPower)
        rrd(DayN, 2) = mean(r.peakNormedPower);
    end

    % Display the first value (duration) for this day
    rrd(DayN)
    toc
end

% After this loop, 'rrd' contains the average duration (col1) and average
% power (col2) for each day. You can save or further analyze these results.